# Generated by Django 4.2.9 on 2024-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='days_per_week',
            field=models.IntegerField(default=0, verbose_name='How many days a week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='grade',
            field=models.CharField(default=0, max_length=200, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='location',
            field=models.CharField(default=0, max_length=1000, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='monthly_salary',
            field=models.IntegerField(default=0, verbose_name='Monthly Salary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='pref_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=20, verbose_name='Preferred Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='student_count',
            field=models.IntegerField(default=0, verbose_name='Student Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='subjects',
            field=models.CharField(default=0, max_length=1000, verbose_name='Subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='teaching_time',
            field=models.CharField(default=0, max_length=200, verbose_name='Teaching Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='type',
            field=models.CharField(default=0, max_length=200, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
