# Generated by Django 4.2.9 on 2024-01-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0004_tuitionapplicationadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionapplication',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
